# wrangler.toml (wrangler v3.78.6^)
name = "libre-subs"
main = "./.output/server/index.mjs"
compatibility_date = "2025-02-14"
toconfig = "./tsconfig.json"

minify = true

[observability]
enabled = true
head_sampling_rate = 1

[build]
command = "pnpm build:cloudflare"
watch_dir = "src"
